# Generated by Django 5.0.8 on 2024-08-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_member_joined_date_member_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="location",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
